service: image-api
frameworkVersion: '3'
# configValidationMode: error

plugins:
  - serverless-webpack
  - serverless-offline
  # - serverless-dotenv-plugin
# package:
#   individually: true

# useDotenv: true

custom:
  fileUploadBucketName: image.s3.bucket
  webpack:
    webpackConfig: 'webpack.config.ts' # Name of webpack configuration file
    includeModules: true # Node modules configuration for packaging
    packager: 'npm' # Packager that will be used to package your external modules

provider:
  name: aws
  region: us-east-1
  runtime: nodejs14.x
  stage: dev
  environment:
    user_pool_id: { Ref: UserPool }
    client_id: { Ref: UserClient }
    FILE_UPLOAD_BUCKET_NAME: ${self:custom.fileUploadBucketName}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - cognito-idp:AdminInitiateAuth
            - cognito-idp:AdminCreateUser
            - cognito-idp:AdminSetUserPassword
          Resource: '*'

        - Effect: Allow
          Action:
            - s3:*
          Resource:
            - arn:aws:s3:::${self:custom.fileUploadBucketName}/*

        - Effect: Allow
          Action:
            - dynamodb:*
          Resource:
            - arn:aws:dynamodb:us-east-1:513476794027:table/ImageTable

functions:
  signupUser:
    handler: src/functions/signup/handler.signup
    events:
      - httpApi:
          path: /signup
          method: post
          # cors: true

  loginUser:
    handler: src/functions/login/handler.login
    events:
      - httpApi:
          path: /login
          method: post
          # cors: true

  imageUpload:
    handler: src/functions/imageUpload/handler.imageUpload
    events:
      - http:
          path: /imageUpload
          method: post
          cors: true
          authorizer:
            name: PrivateAuthorizer
            type: COGNITO_USER_POOLS
            arn:
              Fn::GetAtt:
                - UserPool
                - Arn
            claims:
              - email

resources:
  Resources:
    UserPool:
      Type: AWS::Cognito::UserPool
      Properties:
        UserPoolName: image-auth-pool
        Schema:
          - Name: email
            Required: true
            Mutable: true
        Policies:
          PasswordPolicy:
            MinimumLength: 6
        AutoVerifiedAttributes: ['email']

    UserClient:
      Type: AWS::Cognito::UserPoolClient
      Properties:
        ClientName: user-pool-ui
        GenerateSecret: false
        UserPoolId: { Ref: UserPool }
        AccessTokenValidity: 5
        IdTokenValidity: 5
        ExplicitAuthFlows:
          - 'ADMIN_NO_SRP_AUTH'

    ImageS3Bucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.fileUploadBucketName}
        AccessControl: PublicRead

    UserTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ImageTable
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
