service: image-api
frameworkVersion: '3'

plugins:
  - serverless-webpack
  - serverless-offline
  # - serverless-dotenv-plugin
# package:
#   individually: true

# useDotenv: true

custom:
  webpack:
    webpackConfig: 'webpack.config.ts' # Name of webpack configuration file
    includeModules: true # Node modules configuration for packaging
    packager: 'npm' # Packager that will be used to package your external modules
    # excludeFiles: src/**/*.test.js # Provide a glob for files to ignore

provider:
  name: aws
  region: us-east-1
  runtime: nodejs14.x
  environment:
    user_pool_id: { Ref: UserPool }
    client_id: { Ref: UserClient }
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - cognito-idp:AdminInitiateAuth
            - cognito-idp:AdminCreateUser
            - cognito-idp:AdminSetUserPassword
          Resource: '*'

        # - Effect: Allow
        #   Action:
        #     - dynamodb:*
        #   Resource:
        #     - arn:aws:dynamodb:us-east-1:513476794027:table/UserTable

functions:
  signupUser:
    handler: src/functions/signup/handler.signup
    events:
      - httpApi:
          path: /signup
          method: post
          # cors: true

  loginUser:
    handler: src/functions/login/handler.login
    events:
      - httpApi:
          path: /login
          method: post
          # cors: true

  privateAPI:
    handler: src/functions/imageUpload/handler.imageUpload
    events:
      - http:
          path: /imageUpload
          method: post
          cors: true
          authorizer:
            name: PrivateAuthorizer
            type: COGNITO_USER_POOLS
            arn:
              Fn::GetAtt:
                - UserPool
                - Arn
            claims:
              - email

resources:
  Resources:
    UserPool:
      Type: AWS::Cognito::UserPool
      Properties:
        UserPoolName: image-auth-pool
        Schema:
          - Name: email
            Required: true
            Mutable: true
        Policies:
          PasswordPolicy:
            MinimumLength: 6
        AutoVerifiedAttributes: ['email']

    UserClient:
      Type: AWS::Cognito::UserPoolClient
      Properties:
        ClientName: user-pool-ui
        GenerateSecret: false
        UserPoolId: { Ref: UserPool }
        AccessTokenValidity: 5
        IdTokenValidity: 5
        ExplicitAuthFlows:
          - 'ADMIN_NO_SRP_AUTH'

    # UserTable:
    #   Type: AWS::DynamoDB::Table
    #   Properties:
    #     TableName: UserTable
    #     BillingMode: PAY_PER_REQUEST
    #     AttributeDefinitions:
    #       - AttributeName: id
    #         AttributeType: S
    #     KeySchema:
    #       - AttributeName: id
    #         KeyType: HASH
